;METADATA=(Diff=true, UseCommands=true)
[/Script/BattleX.BXBehaviorSettings]
RelationTags=(TagName="BXBehavior.Walk")
RelationTags=(TagName="BXBehavior.Run")
RelationTags=(TagName="BXBehavior.Sprint")
RelationTags=(TagName="BXBehavior.Jump")
RelationTags=(TagName="BXBehavior.Landed")
RelationTags=(TagName="BXBehavior.LowPrioritySkill")
RelationTags=(TagName="BXBehavior.HighPrioritySkill")
RelationTags=(TagName="BXBehavior.ParallelSkill")
RelationTags=(TagName="BXBehavior.Defense")
RelationTags=(TagName="BXBehavior.Block")
RelationTags=(TagName="BXBehavior.Parry")
RelationTags=(TagName="BXBehavior.Dodge")
RelationTags=(TagName="BXBehavior.PerfectDodge")
ExpelRelations=(((TagName="BXBehavior.LowPrioritySkill"), (GameplayTags=((TagName="BXBehavior.Walk"),(TagName="BXBehavior.Run"),(TagName="BXBehavior.Sprint")))),((TagName="BXBehavior.Jump"), (GameplayTags=((TagName="BXBehavior.LowPrioritySkill"),(TagName="BXBehavior.HighPrioritySkill"),(TagName="BXBehavior.Defense"),(TagName="BXBehavior.Block"),(TagName="BXBehavior.Parry"),(TagName="BXBehavior.Dodge"),(TagName="BXBehavior.PerfectDodge")))))
RejectRelations=(((TagName="BXBehavior.LowPrioritySkill"), (GameplayTags=((TagName="BXBehavior.Walk"),(TagName="BXBehavior.Run"),(TagName="BXBehavior.Sprint")))),((TagName="BXBehavior.Jump"), (GameplayTags=((TagName="BXBehavior.LowPrioritySkill"),(TagName="BXBehavior.HighPrioritySkill"),(TagName="BXBehavior.Defense"),(TagName="BXBehavior.Block"),(TagName="BXBehavior.Parry"),(TagName="BXBehavior.Dodge"),(TagName="BXBehavior.PerfectDodge")))))

